#!/usr/bin/env python3
"""Embed the AEGIS web UI (desktop/web/**) into a single C++ header of byte
arrays, so the desktop binary is fully self-contained (no external files to
ship). Run from anywhere:

    python3 tools/embed_assets.py web src/assets_generated.h
"""
import os, sys

MIME = {
    ".html": "text/html; charset=utf-8",
    ".css":  "text/css; charset=utf-8",
    ".js":   "application/javascript; charset=utf-8",
    ".json": "application/json; charset=utf-8",
    ".png":  "image/png",
    ".svg":  "image/svg+xml",
    ".ico":  "image/x-icon",
    ".woff2":"font/woff2",
    ".map":  "application/json; charset=utf-8",
}

def main():
    web_dir = sys.argv[1] if len(sys.argv) > 1 else "web"
    out = sys.argv[2] if len(sys.argv) > 2 else "src/assets_generated.h"
    files = []
    for root, _, names in os.walk(web_dir):
        for n in sorted(names):
            full = os.path.join(root, n)
            rel = "/" + os.path.relpath(full, web_dir).replace(os.sep, "/")
            files.append((rel, full))
    files.sort()

    os.makedirs(os.path.dirname(out) or ".", exist_ok=True)
    total = 0
    with open(out, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by tools/embed_assets.py — do not edit.\n")
        f.write("#pragma once\n#include <unordered_map>\n#include <string>\n#include <cstddef>\n\n")
        f.write("namespace aegis_assets {\n")
        f.write("struct Asset { const unsigned char* data; size_t size; const char* mime; };\n\n")
        entries = []
        for i, (rel, full) in enumerate(files):
            with open(full, "rb") as fh:
                blob = fh.read()
            total += len(blob)
            ext = os.path.splitext(full)[1].lower()
            mime = MIME.get(ext, "application/octet-stream")
            f.write("static const unsigned char a%d[] = {" % i)
            f.write(",".join(str(b) for b in blob))
            if not blob:
                f.write("0")  # avoid zero-size array (non-standard)
            f.write("};\n")
            size_expr = "%d" % len(blob)
            entries.append((rel, "a%d" % i, size_expr, mime))
        f.write("\ninline const std::unordered_map<std::string, Asset>& table() {\n")
        f.write("  static const std::unordered_map<std::string, Asset> m = {\n")
        for rel, var, size_expr, mime in entries:
            esc = rel.replace("\\", "\\\\").replace('"', '\\"')
            f.write('    {"%s", {%s, %s, "%s"}},\n' % (esc, var, size_expr, mime))
        f.write("  };\n  return m;\n}\n")
        f.write("}  // namespace aegis_assets\n")
    print("embedded %d files, %d bytes -> %s" % (len(files), total, out))

if __name__ == "__main__":
    main()
